// Code generated by tools/codegen from the MEOS sources. DO NOT EDIT.
//
// Regenerate with:
//
//	go run ./tools/codegen -mobilitydb <checkout> -o catalog_gen.go
//
// The sources read are meos/src/temporal/meos_catalog.c (the type names, each
// temporal type's base and bounding box, and the predicates temporal_type,
// tnumber_type, tspatial_type and temptype_supports_linear) and
// meos/src/temporal/type_out.c (temptype_as_mfjson_sb).

package main

// TemporalType is one MEOS temporal type, as MEOS's own catalog describes it.
// MFJSON is empty for a type asMFJSON does not write, so an empty token is what
// says a type has no MF-JSON form.
type TemporalType struct {
	Name    string
	Base    string
	Box     string
	MFJSON  string
	Spatial bool
	Number  bool
	Linear  bool
}

// temporalTypes is every temporal type MEOS declares, ordered by name.
var temporalTypes = []TemporalType{
	{Name: "tbigint", Base: "int8", Box: "tbox", MFJSON: "MovingBigInteger", Spatial: false, Number: true, Linear: false},
	{Name: "tbool", Base: "bool", Box: "tstzspan", MFJSON: "MovingBoolean", Spatial: false, Number: false, Linear: false},
	{Name: "tcbuffer", Base: "cbuffer", Box: "stbox", MFJSON: "MovingCircularBuffer", Spatial: true, Number: false, Linear: true},
	{Name: "tdouble2", Base: "double2", Box: "tstzspan", MFJSON: "", Spatial: false, Number: false, Linear: true},
	{Name: "tdouble3", Base: "double3", Box: "tstzspan", MFJSON: "", Spatial: false, Number: false, Linear: true},
	{Name: "tdouble4", Base: "double4", Box: "tstzspan", MFJSON: "", Spatial: false, Number: false, Linear: true},
	{Name: "tfloat", Base: "float8", Box: "tbox", MFJSON: "MovingFloat", Spatial: false, Number: true, Linear: true},
	{Name: "tgeogpoint", Base: "geography", Box: "stbox", MFJSON: "MovingPoint", Spatial: true, Number: false, Linear: true},
	{Name: "tgeography", Base: "geography", Box: "stbox", MFJSON: "MovingGeometry", Spatial: true, Number: false, Linear: false},
	{Name: "tgeometry", Base: "geometry", Box: "stbox", MFJSON: "MovingGeometry", Spatial: true, Number: false, Linear: false},
	{Name: "tgeompoint", Base: "geometry", Box: "stbox", MFJSON: "MovingPoint", Spatial: true, Number: false, Linear: true},
	{Name: "th3index", Base: "h3index", Box: "stbox", MFJSON: "MovingH3Index", Spatial: true, Number: false, Linear: false},
	{Name: "tint", Base: "int4", Box: "tbox", MFJSON: "MovingInteger", Spatial: false, Number: true, Linear: false},
	{Name: "tjsonb", Base: "jsonb", Box: "tstzspan", MFJSON: "MovingJsonb", Spatial: false, Number: false, Linear: false},
	{Name: "tnpoint", Base: "npoint", Box: "stbox", MFJSON: "MovingNetworkPoint", Spatial: true, Number: false, Linear: true},
	{Name: "tpcpatch", Base: "pcpatch", Box: "tpcbox", MFJSON: "MovingPCPatch", Spatial: true, Number: false, Linear: false},
	{Name: "tpcpoint", Base: "pcpoint", Box: "tpcbox", MFJSON: "MovingPCPoint", Spatial: true, Number: false, Linear: false},
	{Name: "tpose", Base: "pose", Box: "stbox", MFJSON: "MovingPose", Spatial: true, Number: false, Linear: true},
	{Name: "tposechain", Base: "posechain", Box: "stbox", MFJSON: "MovingPoseChain", Spatial: true, Number: false, Linear: true},
	{Name: "tquadbin", Base: "quadbin", Box: "stbox", MFJSON: "MovingQuadbin", Spatial: true, Number: false, Linear: false},
	{Name: "trgeometry", Base: "pose", Box: "stbox", MFJSON: "MovingRigidGeometry", Spatial: true, Number: false, Linear: true},
	{Name: "ts2cell", Base: "s2cell", Box: "stbox", MFJSON: "", Spatial: true, Number: false, Linear: false},
	{Name: "ttext", Base: "text", Box: "tstzspan", MFJSON: "MovingText", Spatial: false, Number: false, Linear: false},
}

// temporalTypeByName indexes temporalTypes by the MEOS type name.
var temporalTypeByName = func() map[string]*TemporalType {
	m := make(map[string]*TemporalType, len(temporalTypes))
	for i := range temporalTypes {
		m[temporalTypes[i].Name] = &temporalTypes[i]
	}
	return m
}()
