// Code generated by tools/codegen from the MEOS-API catalog. DO NOT EDIT.
//
// Regenerate with:
//
//	go run ./tools/codegen -catalog <meos-idl.json> -o catalog_gen.go
//
// The source is meos-idl.json#/temporalTypes, which MobilityDB/MEOS-API derives
// from meos/src/temporal/meos_catalog.c (the type names, each temporal type's
// base and bounding box, and the predicates temporal_type, tnumber_type,
// tspatial_type and temptype_supports_linear) and meos/src/temporal/type_out.c
// (temptype_as_mfjson_sb, the MF-JSON type token).

package main

// TemporalType is one MEOS temporal type, as MEOS's own catalog describes it.
// MFJSON is empty for a type asMFJSON does not write, so an empty token is what
// says a type has no MF-JSON form.
type TemporalType struct {
	Name    string
	Base    string
	Box     string
	MFJSON  string
	Spatial bool
	Number  bool
	Linear  bool
}

// temporalTypes is every temporal type MEOS declares, ordered by name.
var temporalTypes = []TemporalType{
	{Name: "tbigint", Base: "int8", Box: "tbox", MFJSON: "MovingBigInteger", Spatial: false, Number: true, Linear: false},
	{Name: "tbool", Base: "bool", Box: "tstzspan", MFJSON: "MovingBoolean", Spatial: false, Number: false, Linear: false},
	{Name: "tcbuffer", Base: "cbuffer", Box: "stbox", MFJSON: "MovingCircularBuffer", Spatial: true, Number: false, Linear: true},
	{Name: "tdouble2", Base: "double2", Box: "tstzspan", MFJSON: "", Spatial: false, Number: false, Linear: true},
	{Name: "tdouble3", Base: "double3", Box: "tstzspan", MFJSON: "", Spatial: false, Number: false, Linear: true},
	{Name: "tdouble4", Base: "double4", Box: "tstzspan", MFJSON: "", Spatial: false, Number: false, Linear: true},
	{Name: "tfloat", Base: "float8", Box: "tbox", MFJSON: "MovingFloat", Spatial: false, Number: true, Linear: true},
	{Name: "tgeogpoint", Base: "geography", Box: "stbox", MFJSON: "MovingPoint", Spatial: true, Number: false, Linear: true},
	{Name: "tgeography", Base: "geography", Box: "stbox", MFJSON: "MovingGeometry", Spatial: true, Number: false, Linear: false},
	{Name: "tgeometry", Base: "geometry", Box: "stbox", MFJSON: "MovingGeometry", Spatial: true, Number: false, Linear: false},
	{Name: "tgeompoint", Base: "geometry", Box: "stbox", MFJSON: "MovingPoint", Spatial: true, Number: false, Linear: true},
	{Name: "th3index", Base: "h3index", Box: "stbox", MFJSON: "MovingH3Index", Spatial: true, Number: false, Linear: false},
	{Name: "tint", Base: "int4", Box: "tbox", MFJSON: "MovingInteger", Spatial: false, Number: true, Linear: false},
	{Name: "tjsonb", Base: "jsonb", Box: "tstzspan", MFJSON: "MovingJsonb", Spatial: false, Number: false, Linear: false},
	{Name: "tnpoint", Base: "npoint", Box: "stbox", MFJSON: "MovingNetworkPoint", Spatial: true, Number: false, Linear: true},
	{Name: "tpcpatch", Base: "pcpatch", Box: "tpcbox", MFJSON: "MovingPCPatch", Spatial: true, Number: false, Linear: false},
	{Name: "tpcpoint", Base: "pcpoint", Box: "tpcbox", MFJSON: "MovingPCPoint", Spatial: true, Number: false, Linear: false},
	{Name: "tpose", Base: "pose", Box: "stbox", MFJSON: "MovingPose", Spatial: true, Number: false, Linear: true},
	{Name: "tposechain", Base: "posechain", Box: "stbox", MFJSON: "MovingPoseChain", Spatial: true, Number: false, Linear: true},
	{Name: "tquadbin", Base: "quadbin", Box: "stbox", MFJSON: "MovingQuadbin", Spatial: true, Number: false, Linear: false},
	{Name: "trgeometry", Base: "pose", Box: "stbox", MFJSON: "MovingRigidGeometry", Spatial: true, Number: false, Linear: true},
	{Name: "ts2cell", Base: "s2cell", Box: "stbox", MFJSON: "", Spatial: true, Number: false, Linear: false},
	{Name: "ttext", Base: "text", Box: "tstzspan", MFJSON: "MovingText", Spatial: false, Number: false, Linear: false},
}

// temporalTypeByName indexes temporalTypes by the MEOS type name.
var temporalTypeByName = func() map[string]*TemporalType {
	m := make(map[string]*TemporalType, len(temporalTypes))
	for i := range temporalTypes {
		m[temporalTypes[i].Name] = &temporalTypes[i]
	}
	return m
}()

// MathOp is one MEOS function that takes a temporal number and answers one.
// SQLName is the name the operation carries on every engine, Symbol the MEOS C
// symbol behind it, and Arg the C type of its one further parameter, empty when
// it takes none.
type MathOp struct {
	SQLName string
	Symbol  string
	Arg     string
}

// mathOps is every such function the catalog states, ordered by SQL name.
var mathOps = []MathOp{
	{SQLName: "abs", Symbol: "tnumber_abs", Arg: ""},
	{SQLName: "angularDifference", Symbol: "tnumber_angular_difference", Arg: ""},
	{SQLName: "ceil", Symbol: "tfloat_ceil", Arg: ""},
	{SQLName: "cos", Symbol: "tfloat_cos", Arg: ""},
	{SQLName: "degrees", Symbol: "tfloat_degrees", Arg: "bool"},
	{SQLName: "derivative", Symbol: "temporal_derivative", Arg: ""},
	{SQLName: "exp", Symbol: "tfloat_exp", Arg: ""},
	{SQLName: "floor", Symbol: "tfloat_floor", Arg: ""},
	{SQLName: "ln", Symbol: "tfloat_ln", Arg: ""},
	{SQLName: "log10", Symbol: "tfloat_log10", Arg: ""},
	{SQLName: "radians", Symbol: "tfloat_radians", Arg: ""},
	{SQLName: "round", Symbol: "temporal_round", Arg: "int"},
	{SQLName: "scaleTime", Symbol: "temporal_scale_time", Arg: "const Interval *"},
	{SQLName: "setInterp", Symbol: "temporal_set_interp", Arg: "interpType"},
	{SQLName: "shiftTime", Symbol: "temporal_shift_time", Arg: "const Interval *"},
	{SQLName: "sin", Symbol: "tfloat_sin", Arg: ""},
	{SQLName: "tAdd", Symbol: "add_tfloat_float", Arg: "double"},
	{SQLName: "tDiv", Symbol: "div_tfloat_float", Arg: "double"},
	{SQLName: "tMul", Symbol: "mul_tfloat_float", Arg: "double"},
	{SQLName: "tSub", Symbol: "sub_tfloat_float", Arg: "double"},
	{SQLName: "tan", Symbol: "tfloat_tan", Arg: ""},
	{SQLName: "trend", Symbol: "tnumber_trend", Arg: ""},
}

// mathOpBySQLName indexes mathOps by the SQL name. A name several functions
// carry keeps them all, so a caller resolves it rather than reading whichever
// entry a map happened to hold.
var mathOpBySQLName = func() map[string][]*MathOp {
	m := map[string][]*MathOp{}
	for i := range mathOps {
		m[mathOps[i].SQLName] = append(m[mathOps[i].SQLName], &mathOps[i])
	}
	return m
}()
