//go:build meos

// Code generated by tools/codegen from the MEOS-API catalog. DO NOT EDIT.
//
// Regenerate with:
//
//	go run ./tools/codegen -catalog <meos-idl.json> -o-meos mathops_meos_gen.go
//
// One case per operation the catalog states over a temporal number, calling the
// MEOS symbol the catalog names. An operation whose further parameter cannot be
// filled from the single value a query carries gets no case.

package main

/*
#cgo pkg-config: meos
#include <meos.h>
*/
import "C"

// callMathOp applies the operation named by its SQL name to a temporal number,
// filling any further parameter from arg. It answers false when the operation
// is not one this dispatch serves, which the caller reports as an unknown
// operation rather than as a failed call.
func callMathOp(sqlName string, temp *C.Temporal, arg float64) (*C.Temporal, bool) {
	switch sqlName {
	case "abs":
		return C.tnumber_abs(temp), true
	case "angularDifference":
		return C.tnumber_angular_difference(temp), true
	case "ceil":
		return C.tfloat_ceil(temp), true
	case "cos":
		return C.tfloat_cos(temp), true
	case "degrees":
		return C.tfloat_degrees(temp, arg != 0), true
	case "derivative":
		return C.temporal_derivative(temp), true
	case "exp":
		return C.tfloat_exp(temp), true
	case "floor":
		return C.tfloat_floor(temp), true
	case "ln":
		return C.tfloat_ln(temp), true
	case "log10":
		return C.tfloat_log10(temp), true
	case "radians":
		return C.tfloat_radians(temp), true
	case "round":
		return C.temporal_round(temp, C.int(arg)), true
	case "sin":
		return C.tfloat_sin(temp), true
	case "tAdd":
		return C.add_tfloat_float(temp, C.double(arg)), true
	case "tDiv":
		return C.div_tfloat_float(temp, C.double(arg)), true
	case "tMul":
		return C.mul_tfloat_float(temp, C.double(arg)), true
	case "tSub":
		return C.sub_tfloat_float(temp, C.double(arg)), true
	case "tan":
		return C.tfloat_tan(temp), true
	case "trend":
		return C.tnumber_trend(temp), true
	}
	return nil, false
}
