// Command codegen writes catalog_gen.go, the tier's table of MEOS temporal
// types, from the MEOS-API catalog.
//
// meos-idl.json is the machine-readable description of the MEOS C library that
// MobilityDB/MEOS-API derives from the MEOS headers and sources, and that every
// binding in the ecosystem generates from. Its `temporalTypes` registry states,
// per Temporal<T>, the facts this tier needs: the base type, the bounding box,
// the MF-JSON type token asMFJSON writes, and whether the type is spatial, a
// number, and linearly interpolated. Reading them here is what makes this tier
// a projection of the same catalog as PyMEOS, JMEOS and the rest, rather than a
// reader of MEOS's C with a parse of its own to keep working.
//
// Usage:
//
//	go run ./tools/codegen -catalog <meos-idl.json> -o catalog_gen.go
//
// The catalog is derived, never committed: CI generates it from a MobilityDB
// commit with MobilityDB/MEOS-API's provision-meos action, regenerates this
// file against it and refuses a difference, so a type MEOS gains reaches this
// tier as a failing check rather than as silence.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
)

// catalog is the part of meos-idl.json this generator reads.
type catalog struct {
	TemporalTypes map[string]temporalType `json:"temporalTypes"`
}

// temporalType is one entry of the catalog's temporalTypes registry. MFJSON is
// absent for a type asMFJSON does not write, so an empty token is what says a
// type has no MF-JSON form.
type temporalType struct {
	Base    string `json:"base"`
	Box     string `json:"bbox"`
	MFJSON  string `json:"mfjson"`
	Spatial bool   `json:"spatial"`
	Number  bool   `json:"number"`
	Linear  bool   `json:"linear"`
}

func main() {
	path := flag.String("catalog", "meos-idl.json", "the MEOS-API catalog")
	out := flag.String("o", "catalog_gen.go", "file to write")
	flag.Parse()

	raw, err := os.ReadFile(*path)
	if err != nil {
		fail(err)
	}
	var c catalog
	if err := json.Unmarshal(raw, &c); err != nil {
		fail(fmt.Errorf("%s: %w", *path, err))
	}
	if len(c.TemporalTypes) == 0 {
		fail(fmt.Errorf("%s carries no temporalTypes registry: it is older than the "+
			"MEOS-API that states one, or it is not a MEOS-API catalog", *path))
	}

	src, err := render(c.TemporalTypes)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fail(err)
	}
	fmt.Fprintf(os.Stderr, "codegen: %d temporal types written to %s\n", len(c.TemporalTypes), *out)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "codegen:", err)
	os.Exit(1)
}

func render(types map[string]temporalType) ([]byte, error) {
	names := make([]string, 0, len(types))
	for name := range types {
		names = append(names, name)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString(`// Code generated by tools/codegen from the MEOS-API catalog. DO NOT EDIT.
//
// Regenerate with:
//
//	go run ./tools/codegen -catalog <meos-idl.json> -o catalog_gen.go
//
// The source is meos-idl.json#/temporalTypes, which MobilityDB/MEOS-API derives
// from meos/src/temporal/meos_catalog.c (the type names, each temporal type's
// base and bounding box, and the predicates temporal_type, tnumber_type,
// tspatial_type and temptype_supports_linear) and meos/src/temporal/type_out.c
// (temptype_as_mfjson_sb, the MF-JSON type token).

package main

// TemporalType is one MEOS temporal type, as MEOS's own catalog describes it.
// MFJSON is empty for a type asMFJSON does not write, so an empty token is what
// says a type has no MF-JSON form.
type TemporalType struct {
	Name    string
	Base    string
	Box     string
	MFJSON  string
	Spatial bool
	Number  bool
	Linear  bool
}

// temporalTypes is every temporal type MEOS declares, ordered by name.
var temporalTypes = []TemporalType{
`)
	for _, name := range names {
		t := types[name]
		fmt.Fprintf(&b, "\t{Name: %q, Base: %q, Box: %q, MFJSON: %q, Spatial: %t, Number: %t, Linear: %t},\n",
			name, t.Base, t.Box, t.MFJSON, t.Spatial, t.Number, t.Linear)
	}
	b.WriteString(`}

// temporalTypeByName indexes temporalTypes by the MEOS type name.
var temporalTypeByName = func() map[string]*TemporalType {
	m := make(map[string]*TemporalType, len(temporalTypes))
	for i := range temporalTypes {
		m[temporalTypes[i].Name] = &temporalTypes[i]
	}
	return m
}()
`)
	return format.Source(b.Bytes())
}
